import type { NextPage } from 'next'
import Head from 'next/head'
//import 'mapbox-gl/dist/mapbox-gl.css'
import '@mapbox/mapbox-gl-geocoder/dist/mapbox-gl-geocoder.css'
import { useEffect, useState } from 'react'
import { fetchFeatures, useFeatures } from '../hooks/Features'
import { useUser, useSessionContext } from '@supabase/auth-helpers-react'
import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
import { useStore } from '../store'
import Map from '../components/Map'
import SearchBar from '../components/SearchBar'
import SearchDrawer from '../components/version-one/Drawer/SearchDrawer'

const Home: NextPage = ({}) => {
  const [_, setAuth] = useState(false)
  const user = useUser()
  const { supabaseClient } = useSessionContext()
  const authState = useStore((state) => state.authState)
  const searchFocus = useStore((state) => state.searchFocus)
  const mapRef = useStore((state) => state.mapRef)

  return (
    <>
      <Head>
        <title>Bodega Cats</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1 user-scalable=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen overflow-hidden relative">
        <nav className="flex w-full h-20 bg-white justify-between items-center border-solid border-b-[.5px] border-[rgba(0,0,0,.2)] p-3 gap-3">
          <h1 className="text-lg font-baloo text-primaryGold font-bold leading-none">
            Bodega <br /> Cats
            <span className="text-xs font-baloo text-graphite italic font-bold leading-none">
              of nyc
            </span>
          </h1>
          <SearchBar />
          <button
            onClick={() => {
              const coord = mapRef.getCenter()
              console.log(mapRef)
            }}
          >
            {' '}
            CLICK{' '}
          </button>
        </nav>

        <div className="h-container flex flex-row-reverse relative">
          {/*<div className="hidden md:block pb-4 max-w-[400px] w-full h-full overflow-hidden bg-white  border-solid border-r-[.5px] border-[rgba(0,0,0,.2)]">
            <div className="pb-2 pt-4 px-4">
              <SearchBar />
            </div>
            {(searchFocus || searchDrawerIsActive) && <SearchDrawer />}
          </div>*/}
          <Map />
        </div>
      </main>

      <footer></footer>
    </>
  )
}

export default Home
